### ISSUE TITLE
Arguments and results of generate_parameter in aiaccel.optimizer.abstract_optimizer

### ISSUE THREAD

**Issue by tkmnet** [aistairc/aiaccel#100]
**Is your feature request related to a problem? Please describe.**
As much as possible, I want to implement a custom optimizer by only checking the definition of generate_parameter().

**Describe the solution you'd like**
- Provide lists of results as arguments and accept a suggested parameters list as a result of the method.

**Comment by yoshipon** [comment]
@aramoto99 これ対応お願いできますか？ 私も賛成です．
