### ISSUE TITLE
Change `get_grid_options` to be defined in `grid_optimizer`.

### ISSUE THREAD

**Issue by aramoto99** [aistairc/aiaccel#102]
@tkokada @yoshipon 
`get_grid_options`関数の定義場所は，`aiaccel.parameter.get_grid_options`ですが，これはgrid searchでのみ使用する処理です．
そのため，`aiaccel.optimizer.grid_optimizer.get_grid_options`へ移動したほうが良いかと思いましたが，いかがでしょうか？

**Comment by yoshipon** [comment]
ありがとうございます！ よいと思います！
