### ISSUE TITLE
How users give their values to aiaccel?

### ISSUE THREAD

**Issue by tkokada** [aistairc/aiaccel#108]
**Is your feature request related to a problem? Please describe.**
ユーザーがaiaccelに何か値を与えたい時コンフィグレーションファイルを使うのが一般的としますか？
コマンドライン引数で与えようとしましたがstart.pyが意図しない引数は弾くのでコンフィグレーションファイルで与える方法を取りましたが．

**Describe the solution you'd like**
シンプルに意図しない引数は無視すれば良いかなと思います．
どのモジュールにも __init__ で options が渡されるので，ここからコマンドライン引数の値を取れたほうがユーザーにとってはループなどを回しやすいかなと．

**Comment by yoshipon** [comment]
ありがとうございます．

> シンプルに意図しない引数は無視すれば良いかなと思います．
自分はこちら，意図しない引数は弾く枠組みで良いと思います (argparseのデフォルト挙動ですし)

> どのモジュールにも init で options が渡されるので，ここからコマンドライン引数の値を取れたほうがユーザーにとってはループなどを回しやすいかなと．
これに関しては仰る通りだと思います．
Config周りをOmegaConf + Hydraに置き換えると楽だと思いました．
別途Issue立てます．
