### ISSUE TITLE
The random seed specified in Sobol is not working.

### ISSUE THREAD

**Issue by aramoto99** [aistairc/aiaccel#115]
この行でseedを指定するべき？
https://github.com/aistairc/aiaccel/blob/1d3d9da2be9a09efa094ec7d33486b9f5d9b47de/aiaccel/optimizer/sobol_optimizer.py#L35

**Comment by aramoto99** [comment]
To. @tkokada Cc. @yoshipon 
https://github.com/aistairc/aiaccel/blob/1d3d9da2be9a09efa094ec7d33486b9f5d9b47de/aiaccel/optimizer/sobol_optimizer.py#L35
で，`scramble=False`になっていますが，Falseにした場合seedの設定が無効化されるようです．
（デフォルトでは`scramble=True`）
`scramble=True`に変更したほうが良いかと思いますが，変更することで何か不都合はございますでしょうか？

**Comment by tkokada** [comment]
@aramoto99 そうでした．ご指摘ありがとうございます．

リファレンスを見てみると seed で int と numpy.を与えられるようなので近いうちに修正します．

**Comment by tkokada** [comment]
途中で送ってしましました．

numpy => numpy.random.Generator
