### ISSUE TITLE
Use OmegaConf / Hydra to cofigurate the system

### ISSUE THREAD

**Issue by yoshipon** [aistairc/aiaccel#119]
**Is your feature request related to a problem? Please describe.**
aiaccel currently uses a custom implementation to retrieve yaml configurations.

**Describe the solution you'd like**
Replace it to use OmegaConf (+ Hydra).
As discussed in #67 and #108, it would better to use Hydra for updating the config from commandline arguments.

**Comment by aramoto99** [comment]
@yoshipon 
本件，feature/omegaconf ブランチにて仮実装中です．

大きな変化点を連絡致します．

1. config.py で実装していた `Config` や `ConfigEntry` 等を削除．
2. 初期値定義は, `config.py` の `default_config` で辞書形式で定義．
https://github.com/aistairc/aiaccel/blob/feature/omegaconf/aiaccel/config.py
3. コード内で，config関連のアクセスは全て `OmegaConf` の形式に置き換える．

- 改修前 
~~~ 
config.workspace.get()
~~~

- 改修後
~~~
config.generic.workspace
~~~

改修箇所はテストも含め膨大になりそうです．

ひとまず上記の方向性で進めていますが，仕様に関してなにかご意見あればご連絡下さい．

**Comment by tkmnet** [comment]
横から失礼します．
デフォルト値はコードに記述するのではなく，外部のYAMLファイルの記述されていたほうが良いです．
以下のような実装で，パッケージにdefault_config.yamlという完全記述のconfig.yamlがあるイメージです．
```
from importlib import resources
...
    default = OmegaConf.create(resources.read_text('aiaccel', 'default_config.yaml')))
```

**Comment by yoshipon** [comment]
お二人ともありがとうございます．
そうですね，yamlに分けた方が見通しはよくなりそう．
合わせて，aiaccel-init_workspace みたいなコマンドあってもよいかも (default_config.yamlをコピーしたりする)

あと，型チェックみたいなのってできます？ 多分，dataclass使うとできる…？

**Comment by yoshipon** [comment]
https://zenn.dev/dhirooka/articles/f2c12ceae3a0a5
このスタイルで，yamlじゃなくてクラスで書くべきか…？

**Comment by tkmnet** [comment]
型チェックをするのであれば，個人的には，
スキーマ(class)・デフォルトコンフィグ(yaml)・ユーザコンフィグ(yaml)
の３段構成が良いと思います．

**Comment by yoshipon** [comment]
そうですね．迷うところですが，その方が無難な気がします．

**Comment by tkmnet** [comment]
一応，[Yamlでスキーマを書く方法](https://pypi.org/project/yamale/)もあると思います．
YamlやJsonのスキーマ拡張使う利点は型だけではなく，範囲なども指定できることでしょうか．
Enumのチェックもできるのは意外と便利かもしれません．（コンフィグで責任を持つか，参照元が責任を持つかというのはありますが...）

**Comment by aramoto99** [comment]
ひとまず，dataclassを用いて仮実装しています．
https://github.com/aistairc/aiaccel/blob/43d217958a63744d685d49cf34319c8911da2ef5/aiaccel/config.py

本実装が，上記やり取りの内容と異なるようでしたら，コメントにてご指摘下さい．

**Comment by 3bisuoka** [comment]
ご存知でしたら申し訳ありませんが関連モジュールの情報共有ということで．．
Pydantic という data validation & serialization ができる dataclass 系の上位互換のようなモジュールがあるようです.
Web Framework の FastAPI などで使われています．

https://github.com/pydantic/pydantic
https://docs.[pydantic](https://docs.pydantic.dev/).dev/
https://python.astrotech.io/fastapi/pydantic/schema.html

**Comment by tkmnet** [comment]
#135 についても，このissueのドメインかと思いますので，こちらも検討いただければと思います．
`optimize.sobol_scramble` の値の管理はベタ書きしないほうが良いと思います．
