### ISSUE TITLE
The probrem regarding the execution speed of aiaccel.

### ISSUE THREAD

**Issue by 3bisuoka** [aistairc/aiaccel#120]
**Bug??**
The problem regarding the execution speed of aiaccel. The aiaccel seems to be a little slow.
Applying aiaccel to a Sphere function (dim=5) by using RandomOptimizer, it consumes more than 1sec / trial, as shown in the table below.
Is this due to sleep time with respect to optimizer, scheduler, and master?

|  Trial Number |  Total Time [sec]  | 
| --------------- | ------------------  |
|  100                |  160                     |
|  2000              |  3682                   |

**Desktop**
 - OS: Ubuntu 22.04.1 LTS on Windows 11 x86_64
 - Kernel: 5.15.68.1-microsoft-standard-WSL2
 - CPU: Intel i7-8700K (12) @ 3.696GHz

**Comment by tkmnet** [comment]
I think it is natural that a system that adapts polling as a state synchronization method suffers a disadvantage of about 1.5 times the polling interval as a minimum.

**Comment by tkmnet** [comment]
If the problem needs to be resolved, we should quit using the state sync method.

I know two solutions that are the file stream sync and the serverless style. (not standardized names)
- The file stream sync is a method that signals a state update by a file stream reading of the non-write locked file.
- The serverless style is a method that does not use a master node program. In this style, each finalizing step of job locks a global database and invokes a process for generating the next jobs.

**Comment by yoshipon** [comment]
We already quit the state synchronization because all modules are run in a single thread.

**Comment by tkmnet** [comment]
I mean the state synchronization is communication for reporting a result from a calculation node.

**Comment by yoshipon** [comment]
Ah, I see... Thank you 👍

**Comment by 3bisuoka** [comment]
Trying use the aiaccel of [feature/fix-execution-speed](https://github.com/aistairc/aiaccel/tree/feature/fix-execution-speed) branch, I could confirm the improvement regarding its execution speed.

|  Trial Number |  Total Time [sec]  | 
| --------------- | ------------------ |
|  100                |  10                       |
|  2000              |  305                     |

**Comment by 3bisuoka** [comment]
In addition to the above, I show speed test results by using the other optimizers just in case.

・Local Mode
|  Optimizer      |  Trial Number |  Total Time [sec]  | 
| --------------- | --------------- | ------------------ |
|  NelderMead  |  100                |  11                       |
|  NelderMead  |  2000              |  371                     |
|  Sobol             |  100                |  11                       |
|  Sobol             |  2000              |  313                     |
|  TPE                |  100                |  12                       |
|  TPE                |  2000              |  400                     |
