### ISSUE TITLE
Randomly generated initial values are different for each optimizer.

### ISSUE THREAD

**Issue by aramoto99** [aistairc/aiaccel#126]
When Initial is set to random generation, Nelder-Mead and TPE have different initial values for random generation even if the seed value is fixed.

- Nelder Mead result
[nelder-mead.csv](https://github.com/aistairc/aiaccel/files/10053821/nelder-mead.csv)

- TPE result
[tpe.csv](https://github.com/aistairc/aiaccel/files/10053823/tpe.csv)

**Comment by KanaiYuma-aist** [comment]
https://github.com/aistairc/aiaccel/blob/280a401b8499bbf734df4a650539af5a1f78e85e/aiaccel/parameter.py#L158

ここの記述を
`value = rng.uniform(self.lower, self.upper)`
に修正すると、randomの出力値が揃うようになります。
