### ISSUE TITLE
How to train an object detector like YOLOv5?

### ISSUE THREAD

**Issue by AtomScott** [aistairc/aiaccel#14]
**Is your feature request related to a problem? Please describe.**
I want to train an object detector using aiaccel, but I do not know how to do this.

**Describe the solution you'd like**
If possible I want to compare the results and run-time to the hyper-parameter evolution method provided in YOLOv5. 

* [YOLOv5](https://github.com/ultralytics/yolov5)
* [ Hyperparameter Evolution](https://github.com/ultralytics/yolov5/issues/607)

**Questions**
* Is this possible?
* Is there any documentation available?

**Additional context**
This is a question/documentation request rather than a feature request, but I believe the appropriate tags are missing.

**Comment by aramoto99** [comment]
The program to be optimized must be modified for aiaccel.
Follow the instructions in docs/manual_jp.md.
[manual_jp](https://github.com/aistairc/aiaccel/blob/main/docs/manual_jp.md#3-%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0%E3%81%AE%E4%BD%9C%E6%88%90)

The aiaccel results are output to workspace/results.csv after all trials are completed. You can see the output of the optimization function and the changes in the hyperparameters.

---
最適化するプログラムは、aiaccel用に修正する必要があります。
docs/manual_jp.md をご参考下さい。
[manual_jp](https://github.com/aistairc/aiaccel/blob/main/docs/manual_jp.md#3-%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0%E3%81%AE%E4%BD%9C%E6%88%90)

aiaccelの結果は、すべての試行が終了した後、workspace/results.csvに出力されます。
最適化関数の出力とハイパーパラメータの変化を確認できます。

**Comment by yoshipon** [comment]
@AtomScott Thanks for asking about our aiaccel!
We are now working on making documentation available in readthedocs.io so that users can easily access the reference manual.
