### ISSUE TITLE
Modification of Scheduler/job/job.py

### ISSUE THREAD

**Issue by aramoto99** [aistairc/aiaccel#148]
<hr>

【目的】

- schedulerのステートマシン(scheduler/job/job.py)の処理において，現状，`abci`と`local`で条件分岐で処理が別れています．今後，`resource type`の種類が増える可能性があるため，現在の構成では`job.py`に全て記述する必要があり，保守性の低下が懸念されます．そのため，現在の`job.py`を基底クラス化し，`resource type`毎に派生クラス作成する構成に変更します．

【概要】

現在の`job.py`では，

1. Jobクラス: ステートマシン制御 (実行，状態取得など) 
2. Modelクラス: ステートマシンの状態毎の処理(関数)を定義 

があります．Jobクラスは現時点で`abci`と`local`で処理が別れている箇所が無く，今後も分岐する可能性は低いと考え，`resource type`毎に作成せず共通処理として`job.py`に残します．<br>
Modelクラスのみ`resource type`毎に作成する構成を考えています．
次のような構成にする予定です．
```
job
- job.py
- model
    - abstract_model.py
    - abci_model.py
    - local_model.py 
```

<hr>

Purpose

In the processing of the scheduler state machine (scheduler/job/job.py), processing is currently separated by a conditional branch between abci and local. Since there is a possibility that the number of resource types will increase in the future, the current configuration requires all resource types to be described in job.py, which may reduce maintainability. Therefore, the current job.py should be made into a base class, and a derived class should be created for each resource type.

<br>

Outline

In the current job.py, 

1. Job class: State machine control (execution, state acquisition, etc.)
2. Model class: defines processing (functions) for each state of the state machine

The Job class does not separate abci and local processing at this point, and is unlikely to diverge in the future, so it is left in job.py as a common process instead of being created for each resource type.
Only the Model class will be created for each resource type.
The configuration will be as follows.
```
job
- job.py
- model
    - abstract_model.py
    - abci_model.py
    - local_model.py 
```

**Comment by yoshipon** [comment]
ありがとうございます！ よさげです．
