### ISSUE TITLE
Occur shutil.Error in move_completed_data. ([Errno 2] No such file or directory)

### ISSUE THREAD

**Issue by aramoto99** [aistairc/aiaccel#151]
最適化処理後、workspaceディレクトリはresultsディレクトリにコピーされます。
コピー中にsqliteジャーナルファイルが削除された場合、本エラーが発生する可能性があります。

【対策】
他のファイル操作系処理と同様に，リトライ処理の追加で対処予定です．
→ workspace.pyのmove_completed_dataに，リトライ処理を追加．

**Comment by tkmnet** [comment]
横から失礼します．
このような処理でリトライ使用するのは，あまり行儀の良い方法ではないと思います．
ジャーナルファイルが原因で，ジャーナルファイルをコピーする必要がないのであれば，コピーの除外リストに追加してはどうでしょうか？

**Comment by yoshipon** [comment]
とりあえず，緊急対応かなと思ってマージしました．tkmnetさんの指摘通り修正お願いします．
