### ISSUE TITLE
Implementation of log-scaled grid points generation

### ISSUE THREAD

**Issue by styamamoto** [aistairc/aiaccel#154]
In aiaccel.optimizer.grid_optimizer.generate_grid_points, I am concerned about the following code used when `log=True`. 
In particular,
- definition of `lower_x` and `upper_x`
- update method of `x` in while loop
```
        base, log, step = get_grid_options(p.name, config)
        lower = p.lower
        upper = p.upper
        n = int((upper - lower) / step) + 1

        if log:
            lower_x = lower ** base
            upper_x = upper ** base
            x = lower_x
            new_param['parameters'] = []

            while x < upper_x or math.isclose(x, upper_x, abs_tol=1e-10):
                new_param['parameters'].append(math.log(x, base))
                x += step

            new_param['parameters'].append(upper)
        else:
            new_param['parameters'] = [lower + i * step for i in range(0, n)]
```

I'm not sure, but I think what the author wanted to do is; 
```
        base, log, step = get_grid_options(p.name, config)
        lower = p.lower
        upper = p.upper

        if log:
            lower_x = base ** lower
            upper_x = base ** upper
            step_x = base ** step
            x = lower_x
            new_param['parameters'] = []
            while x < upper_x or math.isclose(x, upper_x, abs_tol=1e-10):
                new_param['parameters'].append(x)
                x *= step_x
            new_param['parameters'].append(upper)
        else:
            n = int((upper - lower) / step) + 1
            new_param['parameters'] = [lower + i * step for i in range(0, n)]
```
Please confirm this.

**Comment by yoshipon** [comment]
Agree... Thanks a lot.
Could you make PR...?

**Comment by styamamoto** [comment]
In my understanding, current aiaccel always requires to set `log`, `base`, and `step` for the grid optimizer.

On the orher hand, Optuna's [suggest_float()](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.trial.Trial.html#optuna.trial.Trial.suggest_float) does not use the log and step options simultaneously, and does not have the base option (is this more suitable for actual uses?).

**Comment by tkmnet** [comment]
I forked the issue.
This issue's content is maybe a bug. Therefore, this problem should be fixed on the current implementation philosophy, either way.
