### ISSUE TITLE
The budget-specified grid search

### ISSUE THREAD

**Issue by tkmnet** [aistairc/aiaccel#155]
This issue is forked from #154.

**Is your feature request related to a problem? Please describe.**
I want the budget-specified grid search option in the grid-search optimizer.
The current grid-search optimizer creates suggestion points based on step specifications. However, I think many experimental cases decide the points from a limitation of budget. Moreover, the step on a log scale is not straightly understandable.

I imagine the step-specified implementation is used because there is a case the weights of parameters for the search are not equal.
In that case, I want to specify the number of points for each parameter.

**Describe the solution you'd like**
Make the step optional specification and create suggestions based on a budget, when the step is not specified.
The priority for the points creation rule is
global budget > the order of parameter description > step or points number specified > non-specified.
The non-specified parameters are evenly assigned points from the remaining of the global budget.

**Comment by yoshipon** [comment]
Completely agree.
