### ISSUE TITLE
Miss-substitution of optional parameters?

### ISSUE THREAD

**Issue by styamamoto** [aistairc/aiaccel#158]
https://github.com/aistairc/aiaccel/blob/94661ff9ab63694f9c3e1ce9224198916cec69c2/aiaccel/parameter.py#L134-L138
Is this an intended code?
An option `step` is overwritten by `base`.

Note that this probably has no effect explicitly.
This is because a Config instance is used instead of the Hyperparamter instance, when the option `base` is required in aiaccel.optimizer.grid_optimizer.get_grid_options().

**Comment by tkmnet** [comment]
We would like to write test codes that can detect such mistakes...

**Comment by tkmnet** [comment]
I think the implementation is able to replace to like below. It is safer.
```
...
        self.log = parameter.get('log', False)
        self.lower = parameter.get('lower', None)
...
```
Moreover, the test code should be modified to make the problem detectable.
