### ISSUE TITLE
Modify the optimizer that supports categotical variables so that ordinal variables can also be used.

### ISSUE THREAD

**Issue by aramoto99** [aistairc/aiaccel#175]
`categorical`型をサポートしているoptimizerで、`ordinal`型も使用できるように修正します．
現状，`categorical`をサポートしているのは，`TPE` と `Grid search` です．
- `TPE optimzier` で, `ordinal` 型をサポートするように変更します．
(`Grid search`  は 既に`categorical`型と `ordinal`型をサポートしていますので，変更はありません．)

**Comment by styamamoto** [comment]
一応ですが，現状の `Random` も `categorical` 型と `ordinal` 型の両方をサポートしていた気がします．
(変更は不要だと思いますが)

**Comment by styamamoto** [comment]
素人考えですが，`ordinal` 型の場合 `sequence` のインデックスを予測させるようにすると，選択肢の前後関係が意識されるので， `categorical` 型と差別化できるような気がしますが，如何でしょうか？
```
type: ordinal
sequence: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
```
のとき，オプティマイザは実効的には
```
type: uniform_int
lower: 0
uppert: 10
```
で最適化を行うイメージです．
この方法だと，Nelder-Mead に `ordinal` 型をサポートさせられると思うのですが．．．

**Comment by styamamoto** [comment]
別のイシューかもしれませんが，
この実装が数学的に意味のある実装なら，対数スケールでの探索も有意義な気がします．
log: true の場合には内部で 10^x の x を最適化するイメージです．

こういう実装があると，以前 mtg で話があったように
「Grid が上手くいかないから NelderMead を試してみよう」，
と思ったときに，オプティマイザの欄だけ書き換えれば動かせるので，
使い勝手も向上するのではないでしょうか．
