### ISSUE TITLE
Cannot save data with data type numpy.float64 in yaml file.

### ISSUE THREAD

**Issue by aramoto99** [aistairc/aiaccel#180]
データ型がnumpy.float64のデータをyaml形式で保存し，yaml.load()で呼出すとエラーが発生する．
[参考]
https://stackoverflow.com/questions/40691311/save-results-in-yaml-file-with-python

[対処予定]
1. numpy.float64をstr()し，yamlで保存
2. yaml読み込み時に `yaml.Unsafeloader` を 使用

2で対応予定．

**Comment by styamamoto** [comment]
python_local で実行した場合
- .hp ファイル群は正常に生成される，
- final_result.result ファイルが文字化け?した状態で生成される，

という現象を確認しました．

**Comment by styamamoto** [comment]
yaml.load() する際に Loader を yaml.Unsafeloader にする方法もあるみたいです．
[参考]
https://github.com/yaml/pyyaml/issues/286
