### ISSUE TITLE
There are a lot of mypy errors.

### ISSUE THREAD

**Issue by styamamoto** [aistairc/aiaccel#203]
Mypy で aiaccel の型チェックを行うと多くのエラーが検出されます．
以下のようなエラーが多いように思われます．

1. Incompatible types in assignment (expression has type **"..."**, variable has type **"None"**)
クラスコンストラクタ内において `None` で初期化したメンバに，後から意味のあるインスタンスを代入しようとした場合． 

2. **”None”** has no attribute **"..."** 
クラスコンストラクタ内において `None` で初期化したメンバのメソッド・メンバにアクセスしようとした場合． 

3. Item **"None"** of **"Union[...]"** (または **"Optional[...]”**) has no attribute **"..."**.
Union や Optional として定義されている引数や変数のメソッド・メンバにアクセスしようとした場合．

4. Incompatible default for argument **"..."** (default has type "None", argument has type **"..."**)
キーワード引数を型ヒントと異なる変数で初期化しようとした場合．*e.g.* `def sample(rng: RandomState = None)`

これらのエラーを解消するためには，例外の発生が必要になる箇所などもあり，コードの修正が必要になる場合もあります．
対応できる個所から，順次解消していきたいと思います．

**Comment by styamamoto** [comment]
1. と 2. についての解消案．

例として，以下のようなクラスを考えます．(`integer`, `floating` というメンバを持つが，これらの初期化のタイミングがインスタンス化と異なる)
```python
class Example:
    def __init__(self) -> None:
        self.integer = None
        self.floating = None

    def subs(self, integer: int, floating: float) -> None:
        self.integer = integer
        self.floating = floating

    def sum(self) -> float:
        return self.integer + self.floating

````

mypy でチェックすると以下のエラーが発生します．
```bash
class_member.py:10: error: Incompatible types in assignment (expression has type "int", variable has type "None")  [assignment]
class_member.py:11: error: Incompatible types in assignment (expression has type "float", variable has type "None")  [assignment]
class_member.py:14: error: Unsupported left operand type for + ("None")  [operator]
```
以下のように書き換えることで，エラーを解消できます．
```python
class Example:
    def __init__(self) -> None:
        # self.integer = None
        # self.floating = None
        self.integer: int
        self.floating: float

    def subs(self, integer: int, floating: float) -> None:
        self.integer = integer
        self.floating = floating

    def sum(self) -> float:
        return self.integer + self.floating

````

注意：この書き換えを行うと，`if self.integer is None` のような分岐が使用できなくなります．その場合，
```python
if hasattr(self, 'integer'):
    # Initialized
    ...
else:
    # Not initialized
    ...

```
で判定します．何か値が代入され，初期化されている場合 `True` を，初期化されていなければ `False` を返します．

他に良い方法があれば，コメントをお願いいたします．

**Comment by yoshipon** [comment]
提案ありがとうございます．
`hasattr` はコスト高そうな印象がありますね…

多分，本来的には，
1. `__init__` のタイミングで `None` でなくインスタンスを代入する
2. いつ `None` じゃなくなるのか分からないなら，ちゃんと `self.xxx is not None` 確認する
必要がある気がしますね．

少しずつで良いと思うので，ご対応頂けると嬉しく… 私もどこかでやりたいです．

**Comment by styamamoto** [comment]
この issue が目指すことが何なのかを確認したいです．
1. mypy のエラーの解消
2. 型安全なコードの実装

型安全なコード (2.) は mypy エラーを解消しますが，mypy エラーが出ない (1.) ならば型安全というわけではないと思われます．
実際，`typing.Any` でアノテーションすれば，多くのエラーを消すことができます．

---
以下，補足と提案．


例えば，以下のコードでは，`self.lower` や `self.upper` といったメンバ変数の型は `typing.Union[bool, int, float, list[Any], None]` と推定されます．
そのため，`sample()` メソッドにおいて `RandomState.randint()` などに引数を渡した時点でエラーが生じます．

```python
class HyperParameter:
    def __init__(self, parameter: dict[str, bool | int | float | list]) -> None:
        self.name = parameter['name']
        self.type = parameter['type']
        self.lower = parameter.get('lower', None)
        self.upper = parameter.get('upper', None)

    def sample(self, rng: RandomState) -> dict:
        if self.type == 'int':
            value = rng.randint(self.lower, self.upper)
        elif self.type == 'float':
            value = rng.uniform(self.lower, self.upper)
        else:
            raise TypeError(
                f'Invalid hyper parameter type: {self.type}')
        return {'name': self.name, 'type': self.type, 'value': value}
```
```python
if_branch.py:17: error: Argument 1 to "randint" of "RandomState" has incompatible type "Union[int, float, List[Any], None]"; expected "int"  [arg-type]
if_branch.py:17: error: Argument 2 to "randint" of "RandomState" has incompatible type "Union[int, float, List[Any], None]"; expected "Optional[int]"  [arg-type]
if_branch.py:19: error: Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]
if_branch.py:19: error: Argument 1 to "uniform" of "RandomState" has incompatible type "Union[int, float, List[Any], None]"; expected "float"  [arg-type]
if_branch.py:19: error: Argument 2 to "uniform" of "RandomState" has incompatible type "Union[int, float, List[Any], None]"; expected "float"  [arg-type]
Found 5 errors in 1 file (checked 1 source file)
```

単に mypy のエラーを消したい場合， `HyperParameter.__init__()` の引数の型を `Any` にすればよいです．
```python
    def __init__(self, parameter: Any) -> None:
```
または
```python
    def __init__(self, parameter: dict[str, Any]) -> None:
```

**

一方で，型安全なコード，例えば `parameter['type'] == 'float'` ならば `self.lower` と `self.upper` が `float` である (`None` でもない) ことが保証されるコード，が (この issue で) 必要であれば，パラメータのタイプごとに異なるコンテナを作る，というのが一つの手段かと思います．

```python        
@dataclass
class PredictedValue(ABC):
    name: str
    type: str


@dataclass
class FloatValue(PredictedValue):
    value: float


@dataclass
class HyperParameter(ABC):
    name: str
    type: str
    lower: Any = field(init=False)
    upper: Any = field(init=False)
    ...
    
    @abstractmethod
    def sample(self, rng: RandomState, require_initial: bool = False) -> PredictedValue:
        pass
    
    @abstractmethod
    def cast(self, value: Any) -> PredictedValue:
        pass

    ...


@dataclass
class FloatHyperParameter(HyperParameter)
    lower: float
    upper: float
    ...

    def __post_init__(self):
        if self.log:
            ...
        ...

    def sample(self, rng: RandomStae, require_initial: bool = False) -> FloatValue:
        value = rng.uniform(self.lower, self.upper)
        return self.cast(value)
    
    def cast(self, value: float | numpy.floating) -> FloatValue:
        return FloatValue(name=self.name, type=self.type, value=float(value))

    ...
```
この場合， `if` 文を `isinstance` で分岐させられるようになります．(`tpe_optiizer.create_distribution()` など)
```python
if isinstance(param, FloatHyperParameter):
    ...
elif isinstance(param, IntHyperParameter):
    ...
...
```

**Comment by styamamoto** [comment]
今後の方針 (案)
1. 型安全ではないが `typing.Any` を多用した mypy エラーのないコードを作成 (#242)．
1. github の CI に mypy を組み込む．
1. 型安全なコードを目指したリファクタリングを行う．
    - 以降のコミットでは `typing.Any` は極力禁止．
    - タイプガードができるクラスや仕組みの作成
    - ...

上の流れで進めるなら，CI に mypy が入った時点でこの issue を閉じて，問題の箇所ごとに個別に issue を作成して対処するのが良いかと思います．

**Comment by yoshipon** [comment]
はい，先日議論した通りその方針で良いと思います．来週のミーティングでロジックの修正箇所について詳しく教えてください．

**Comment by styamamoto** [comment]
mypy errors were removed.
However, this does not mean that aiaccel is type-safe.
For type-safe code, individual issues should be opend to discuss implementations, etc.
