### ISSUE TITLE
Change behavior of `import` command

### ISSUE THREAD

**Issue by styamamoto** [aistairc/aiaccel#204]
Currently, `import aiaccel` imports only constants defined in aiaccel/common.py.
I think this behavior is not convenient for developers and especially for users.

Therefore it is better to change the behavior of `import` command.
I believe this improvement paves the way for _library-like aspects_ of the aiaccel in the future.

My suggestions are,
1. `import aiaccel` imports all submodules (commn, config, ...) and all subpackages (cli, master, ...).
2. `common.[CONSTANT NAME]` is imported by `from aiaccel.common import [CONSTANT NAME]`.
3. `from aiaccel.[PACKAGE NAME] import [CLASS NAME]` imports classes and functions defined under subpackages.
    - e.g. `from aiaccel.scheduler import AbciScheduler` (note: `AbciScheduler` is defined in aiaccel/scheduler/abci_scheduler.py)
4. Classes and functions _for users_ are imported by `import aiaccel`.
    - e.g. `from aiaccel import Run` (this is only function for users?)

Please comment about this (Submodule XXX should not be imported, it is better to import class YYY via aiaccel directly, ...)

---

現在，`import aiaccel` は aiaccel/common.py で定義された定数しかインポートできません．
これは開発者にとっても (特に) ユーザにとっても不便だと思います．
そこで，`import` コマンドの挙動を変更したいと思います．

変更案ですが，
1. `import aiaccel` で全てのサブモジュール (common, config など) および全てのサブパッケージ (cli, master, など) をインポートする．
2. `common.[CONSTANT NAME]` は `from aiaccel.common import [COMMON NAME]` でインポートさせるようにする．
3. `from aiaccel.[PACKAGE NAME] import [CLASS NAME]` でサブパッケージ下のクラスや関数をインポートする．
    - 例えば `from aiaccel.scheduler import AbciScheduler` (注: `AbciScheduler` は aiaccel/scheduler/abci_scheduler.py で定義．)
4. ユーザー向けのクラスや関数は `import aiaccel` でインポートする．
    - `from aiaccel import Run`

何か意見があれば，コメントをお願いいたします．(このモジュールはインポートしない方がよい，このクラスを aiaccel.YYY でインポートできた方が良い，など)

**Comment by yoshipon** [comment]
提案ありがとうございます．はい，その方が良いと思います．
そういえば，どこかに循環参照があったかも…

**Comment by styamamoto** [comment]
aiaccel/util/aiaccel.py が \_\_init\_\_.py に含められなかったと思います．
aiaccel.py を別の名前に変更するなどの対応が良いでしょうか？(user_program_wrapper.py など．)
急ぎの改修ではないので，意見を募りたいと思います．

**Comment by styamamoto** [comment]
とりあえず pytest を通るように \_\_init\_\_.py を整備しました．
https://github.com/aistairc/aiaccel/tree/feature/import-behaviors

aiaccel/util の下に置くモジュールについて
循環参照を避けたいので，aiaccel のクラスや関数をインポートしないモジュールに限定した方がよいのではないかと考えています．
該当するモジュールは aiaccel, filesystem, report,  および trialid です．
filesystem と trialid は循環参照の原因になりませんが，aiaccel と report は 循環参照の原因になっています．

report については，cli.start と cli.report しか使用しないため，creation_report と名前を変えて aiaccel.cli の下に配置してみました．

aiaccel についてはまだ \_\_init\_\_.py に含めていません．ユーザーから見やすい位置，かつ PyLocalEcheduler から参照できる位置に配置するのが良いのだと思います．

**Comment by yoshipon** [comment]
ありがとうございます。これ、いったんdraft PRにして議論した方が良さそうですね？

**Comment by yoshipon** [comment]
> `user_program_wrapper.py`
そうですね。ノーアイディアですが、xxx_xxx.pyくらいがいい気がします。
@aramoto99 良いアイディアあったりします…？

**Comment by yoshipon** [comment]
循環参照…
一旦今の方針で良いと思います。

ソフトウェアの設計としてモジュール間が疎結合になってないのは、いつか解消しなきゃいけないですね…
