### ISSUE TITLE
Resumption test fails if resume from 5th parameter twice.

### ISSUE THREAD

**Issue by tkokada** [aistairc/aiaccel#207]
**Describe the bug**
再開テストでは，３回 aiaccel-start がコールされます．１度目は１０パラメータ実行，２度目は５パラメータ実行，３度目は２度目の最後から再開し６パラメータ実行となっています．

**To Reproduce**
例えばresumption_test.pyのどこかにraiseを追加してログを出力して確認できます．
1. 最新のmainをclone
2. [            print('resumption steps finished', final_result_resumption)](https://github.com/aistairc/aiaccel/blob/e5a6ddbcdc47b3400cf55c28305f2183f15c9314/tests/resumption/resumption_test.py#L36)ここの後とかに raise を追加
3. 再開テストの実行，例えばtest_sphere_random_resumption.py
4. pytest -v tests/resumption/sphere/test_sphere_random_resumption.py
5. stdout, stderrを確認できます．３度目の実行時に５番目のパラメータ（IDは４）が再実行されます．

**Expected behavior**
３度目の再開では，６番目のパラメータ（IDは５）から実行される．

**Additional context**
resumption_test.pyでは，再開時に --resume 4 という引数が aiaccel-start に与えられています．

これがバグでは無いという解釈もあり，５個目のパラメータまで終了したけど５個目は再実行して最後まで（１０個目）まで実行するよ，とも取れてこの場合正しい値を返しています．仕様上既に終了したパラメータも再実行するというニーズはあるかもしれませんが，例えば３個目のパラメータから再開した場合ランダムジェネレータを含めて正しく振る舞うよう設計されているかは確認していません．

もしこれがバグであり本当は６個目のパラメータから再開したい場合 --resume 4 はこのままで良いかという問題があります．直感的には --resume の後の数字は５のような気もしますがこれは終了したパラメータ数を表します．次に実行したいパラメータの場合６，終了したパラメータのインデックス（０から始まるので）の場合４ということでしょうか．このインタフェースも検討すれば良いと思います．

ログを確認しただけでプログラムの動作までは追っていないので，ログが間違っていて動作は正しい可能性もあります．

**Comment by aramoto99** [comment]
@tkokada 
解答になっているか分かりませんが, 参考までに...．

`ResumptionTest` で`resume`した場合に`trial_id` `5`が二度実行されるのは，意図通りです．
`resume` 機能は任意の `trial id` から再開出来る仕様であるため，テストでは`--resume` の`trial_id`を意図的に前回終了時のトライアル番号-1にしています．完了している`trial_id`を指定しても，指定した`trial_id`から再実行することを確認するという意図があります．

テストの合否判定は，中断なしで最後まで実行した場合の最終値(user.pyの出力)と，中断して途中再開して最後まで実行した場合の最終値の同値比較をしています．

**Comment by tkokada** [comment]
@aramoto99 
早速ありがとうございます．ひとまず旧タイトルの件は意図的ということでタイトルを変えました．

resumption_test.py の --resume 4 を --resume 5 にすると以下のエラーで停止します．
エラーの通り trial_id 5 の状態は無いよってことですが，当然 trial_id を -1 すれば動作します．

```
Traceback (most recent call last):
  File "/usr/local/bin/aiaccel-start", line 33, in <module>
    sys.exit(load_entry_point('aiaccel==0.0.1', 'console_scripts', 'aiaccel-start')())
  File "/workspaces/aiaccel/aiaccel/cli/start.py", line 65, in main
    module.pre_process()
  File "/workspaces/aiaccel/aiaccel/optimizer/abstract_optimizer.py", line 173, in pre_process
    self.resume()
  File "/workspaces/aiaccel/aiaccel/optimizer/abstract_optimizer.py", line 240, in resume
    self._deserialize(self.options['resume'])
  File "/workspaces/aiaccel/aiaccel/module.py", line 231, in _deserialize
    self.__dict__.update(self.storage.variable.d['state'].get(trial_id).__dict__.copy())
AttributeError: 'NoneType' object has no attribute '__dict__'
```

**Comment by aramoto99** [comment]
@tkokada 

すいません，テストコンセプトに関して，ちょっと勘違いしていました．
ご指摘頂いている通り，trial_id は0開始なので，中断したtrial_id = 4 から再開というのが現在のテストです．
上記で書いている`意図的に前回終了時のトライアル番号-1`のくだりは誤りです．
(他テストの話と混同しておりました，申し訳ございません．)

- 中断時の状態
~~~ bash
╭──────────────────────────────────────────────────────────────────────────────────────────────╮
│trial_id  start_time           end_time             status    job   result             error  │
│──────────────────────────────────────────────────────────────────────────────────────────────│
│0         02/08/2023 12:43:21  02/08/2023 12:43:21  finished  None  0.25                      │
│1         02/08/2023 12:43:21  02/08/2023 12:43:21  finished  None  88.81649667540222         │
│2         02/08/2023 12:43:22  02/08/2023 12:43:22  finished  None  70.28414386723992         │
│3         02/08/2023 12:43:22  02/08/2023 12:43:22  finished  None  58.31626761561506         │
│4         02/08/2023 12:43:22  02/08/2023 12:43:22  finished  None  105.2905226835149         │
╰──────────────────────────────────────────────────────────────────────────────────────────────╯
~~~

- このテストでは，中断時で trial_id = 4 で進んでおり，ご指摘頂いているように，`--resume 4`することでtrial 4 が二度実行されます．
内部では，`--resume n`で指定したtrial情報をクリアして再開処理を実行しますので，動きとしては想定した通りです．

- 再開テストで '--resume 5'でエラーになる件
スナップショットが保存されていないtrial_idを指定すると，提示頂いたようなエラーが出ます．
テストではtrial_id=5のスナップショットデータが無いため，(4完了の時点で処理終了しているため)，エラーになります．
ですので，ResumptionTestではこれまで通り`--resume 4`を指定頂きたく．
ResumptionTestで想定している状況は，trial_id=4の実行途中に何かしらの要因で停止したのちに`--resume 4`することでtrial_id 4から再開というものですが，実際にはResumptionTestではtrial_id=4が最後まで実行されてしまっています．

**Comment by tkokada** [comment]
@aramoto99
なるほど，trial_id 4で途中停止した想定で4から再開ということですね．
５まで実行し再開だったので勝手に解釈していました．
このイシューは close #207 します．
