### ISSUE TITLE
Separate requirements.txt for users and developers

### ISSUE THREAD

**Issue by styamamoto** [aistairc/aiaccel#212]
Current aiaccel/requirements.txt includes all of modules for running aiaccel, testing implementations, and rendering documents.
However, I think only developer need latter two types of modules.
Therefore requirements.txt is better to be separated for pure users and developers.

**Comment by yoshipon** [comment]
ありがとうございます。また時間あるときで良いので、他のライブラリがどう実装しているのかご確認お願いします。
