### ISSUE TITLE
README_jp.md in example/resnet50_cifar10 is missing

### ISSUE THREAD

**Issue by KanaiYuma-aist** [aistairc/aiaccel#227]
**Is your feature request related to a problem? Please describe.**

The separate README for example/resnet50_cifar10 created in the past has been removed and is
[aiaccel.readthedocs.io/](https://aiaccel.readthedocs.io/) and is also not listed.

---

以前作成した example/resnet50_cifar10 用に個別に用意した README が削除されており、
私が確認する限りでは、[aiaccel.readthedocs.io/](https://aiaccel.readthedocs.io/) にも記載されていません。

d0744586eb4fa16477d72182788aadfe1d421d4b で削除された様子です。

青木さん(signateさん)から公開して欲しいとの要望がありました。

**Describe the solution you'd like**

Place it in example/resnet50_cifar10 as in the past.
Alternatively, it can be published there if appropriate.

---

以前と同様に example/resnet50_cifar10 に配置する。
あるいは、適切な場所があればそこで公開する。

**Comment by yoshipon** [comment]
@styamamoto これ経緯とかあります？

**Comment by styamamoto** [comment]
aiaccel/docs/source/examples/abci_nelder_mead.md に移っています．
内容もほとんど変えていないはずです．
aiaccel/examples 以下のディレクトリは，aiaccel の実行に使うファイルだけを置くようにしています．

**Comment by KanaiYuma-aist** [comment]
@styamamoto 
確認しました、ありがとうございます。
こちらのリンクを共有すれば解決しそうですね。
問題が無ければこちらのissueはcloseします。
