### ISSUE TITLE
No need to save the optimization results in yaml format in `work/result/`.

### ISSUE THREAD

**Issue by aramoto99** [aistairc/aiaccel#249]
- The process of storing the results of each job in yaml format in `work/result` can be removed.
- All results are managed by the database and do not need to be stored separately in yaml format.
- It is assumed that users will refer to `work/results.csv` or use the command `aiaccel-view` to view the results.

<hr>

- job毎の結果を `work/result` に yaml 形式で保存する処理は削除しても問題ありません．
- 結果はすべてデータベースによって管理しており，yaml形式で別途保存する必要はありません．
- ユーザーが結果を参照する場合は`work/results.csv`を参照するか，`aiaccel-view`コマンドを使用することを想定しています．

**Comment by styamamoto** [comment]
Verification results also saved as yaml files.
These are not currently stored in the database, but can be obsolete if making verification table in the database instead.

--- 
Verification も yaml で保存されています．
現状では，データベースには保存されていませんが，Verification 用のテーブルをデータベースに作成すれば ymal 形式のファイルを廃止することも可能かと思います．
