### ISSUE TITLE
There is an error when the `goal` setting in config is for multiobjective.

### ISSUE THREAD

**Issue by aramoto99** [aistairc/aiaccel#254]
configのoptimizeの設定がmultiobjective用であるとき，`aiaccel-plot`を実行すると下記のようなエラーとなります．
~~~bash
Traceback (most recent call last):
  File "/home/member/opt/working/new_opt/de/bin/aiaccel-plot", line 33, in <module>
    sys.exit(load_entry_point('aiaccel==0.0.1', 'console_scripts', 'aiaccel-plot')())
  File "/home/member/opt/working/new_opt/de/lib/python3.8/site-packages/aiaccel-0.0.1-py3.8.egg/aiaccel/cli/plot.py", line 82, in main
    plotter = Plotter(config)
  File "/home/member/opt/working/new_opt/de/lib/python3.8/site-packages/aiaccel-0.0.1-py3.8.egg/aiaccel/cli/plot.py", line 26, in __init__
    self.goal = config.goal.get().lower()
AttributeError: 'list' object has no attribute 'lower'
~~~

config.goal.get()は`minimize` or `maximize`ですが，multiobjectiveの時はリストとなります．
例: MOTPE用の設定
~~~python
['minimize', 'minimize']
~~~

例: それ以外
~~~python
'minimize'
~~~

現状では`goal`を参照する処理でmultiobjective用の設定に対応できない箇所が多いです．（文字列として処理しているため）
goalを参照する全ての箇所全で，リストとして処理するように変更したほうが良いのではと思いましたが，いかがでしょうか？

**Comment by aramoto99** [comment]
関連事項

start.pyなどには，multobjectiveのときに特定の処理をskipする処理が入っていますが，この場合，最終結果を印字しないのが若干気になります．

https://github.com/aistairc/aiaccel/blob/3e752cac51c8d103587b13f3240b1f05154da75e/aiaccel/cli/start.py#L145-L149

（本来ならば最終で以下のように best result を表示しますが，multobjective で動かす場合は以下の表示がスキップされる）
~~~bash
Best result    : results/20230323_164810/result/000020.hp
               : -6.866868514019766
Total time [s] : 25
~~~

**Comment by tkokada** [comment]
@aramoto99 ありがとうございます。そうですね。全箇所でリストとして扱ったほうが良いかもしれません。

多目的最適化の場合何をもってベストとするかをユーザーが提供しない限りベストと決めることができませんのでスキップしています。これは打ち合わせでも共有し合意がありました（そろそろこう決まったログとかあった方が良いかもしれませんね）。
