### ISSUE TITLE
Use the latest Flake8 after pytest-flake8's bug is fixed.

### ISSUE THREAD

**Issue by KanaiYuma-aist** [aistairc/aiaccel#27]
**Is your feature request related to a problem? Please describe.**
Update to flake8 occurred on 8/1 (5.00) and the class 'ConfigFileFinder' became unusable and aiaccel tests failed.
Use 4.01 until the error is fixed, and when the flake8 error is fixed, update to the latest version of flake8.

**Describe the solution you'd like**
delete `flake8==4.0.1` from `requirements.txt`

**Comment by yoshipon** [comment]
@KanaiYuma-aist こちらその後どうなっているか確認お願いできますでしょうか．

**Comment by KanaiYuma-aist** [comment]
@yoshipon 
flake8最新版(5.0.4)で確認した所、同様に `ConfigFileFinder` 関連のエラーが出ました。
![Screenshot from 2022-11-17 14-54-45](https://user-images.githubusercontent.com/105629713/202368096-342c638c-619f-4f5b-a20f-90cf8353022a.png)


pytest-flake8 の git にある同様の issues も open のままだったので、未対応の様子です。

**Comment by yoshipon** [comment]
ありがとうございます！
