### ISSUE TITLE
Consider removing unnecessary string operations for hyperparameter data types in aiaccel codebase

### ISSUE THREAD

**Issue by aramoto99** [aistairc/aiaccel#273]
configファイルでハイパラのデータ型を指定する方法として、以下のように指定します。しかし、実際にはHyperParameterクラスで別の文字列に置き換えています。

* `uniform_int`
* `uniform_float`
* `categorical`
* `ordinal`

以下の表は、configファイルでの指定とHyperParameterクラスでの置き換え文字列を示しています。

| 元 (conig) | 変換後(文字列) |
|-------------------|-----------|
|uniform_int    | INT      |
|uniform_float | FLOAT |
|categorical | CATEGORICAL |
ordinal | ORDINAL

###  実行場所
https://github.com/aistairc/aiaccel/blob/a821159d465d289c9d9cca5956ce80f52200f950/aiaccel/parameter.py#L7-L28

https://github.com/aistairc/aiaccel/blob/a821159d465d289c9d9cca5956ce80f52200f950/aiaccel/parameter.py#L54-L58

現状は`uniform_int` → `INT`のような置き換えは不要であると思います．
使用箇所はOptimizerクラスに限定されています．

* 例
https://github.com/aistairc/aiaccel/blob/a821159d465d289c9d9cca5956ce80f52200f950/aiaccel/optimizer/tpe_optimizer.py#L253-L277

上記の文字列操作の処理ですが，削除しても問題ないかと思いますが，いかがでしょうか？

**Comment by yoshipon** [comment]
削除して良いと思います！
