### ISSUE TITLE
Tests take a long time

### ISSUE THREAD

**Issue by KanaiYuma-aist** [aistairc/aiaccel#277]
**Is your feature request related to a problem? Please describe.**

- 現状、テストに掛かる時間が長く（26分〜27分）、これを短くしたい。

**Describe the solution you'd like**

- aiaccel-set-result を subprocess.run で呼び出している箇所に処理時間が掛かっているため、これを subprocess.Popen で置き換える。
  - こちらについては、ブランチ [feature/improve_executing_speed](https://github.com/aistairc/aiaccel/tree/feature/improve_executing_speed) にて仮実装中
- local で実行しているテスト(Resume Test, Supplemental Test)を、pylocalで実行する。
  - Resume Test, Supplemental Test は、基本 optimizer に関するテストでなので、pylocalで実行しても問題ないと考える。
    - scheduler を local, pylocal で切り替えた場合のテストは Optimizer Algorithm Test で実行している。

---

**Is your feature request related to a problem? Please describe.**

- Currently, testing takes a long time (26-27 minutes) and we would like to shorten this time.

**Describe the solution you'd like**.

- The processing time is taking at the point where aiaccel-set-result is called with subprocess.run, so replace this with subprocess.Popen.
- Run tests (Resume Test, Supplemental Test) running locally in pylocal.

**Comment by KanaiYuma-aist** [comment]
@styamamoto 
Supplemental Test については、山本さんが作成したものも含まれているため  pylocal に変えても問題ないかご意見頂けると幸いです。

**Comment by yoshipon** [comment]
提案ありがとうございます．私も気になっていました．
> Resume Test, Supplemental Test は、基本 optimizer に関するテストでなので、pylocalで実行しても問題ないと考える。
こちら自分は問題ない気もしますが，判断つかないので， @tkokada さん， @aramoto99 さんもコメント (👍だけでも) もらえると幸いです．

**Comment by aramoto99** [comment]
関連するテストの項目と，各テストの`Resource Type`を以下に示します．

* Optimizer Algorithm Test
→ `local`
→ `python_local`

* Resume Test
→ `python_local`

* Supplemental Test
→ 任意

`Resource Type`毎のテストを`Optimizer Algorithm Test`で行ったあとで`Supplemental Test`を実行します．

金井さんの意見をなぞる形になりますが，`Supplemental Test`で`Resource Type`に関係ないテストは，`Resource Type` = `python_local`で実施しても大丈夫だと考えます．

**Comment by styamamoto** [comment]
私が書いたテスト (additional_budget_specified_grid_test) には，
Resource Type に関わるような検証は含まれていないはずなので，
`python_local` で実行しても問題ないと思います．
