### ISSUE TITLE
Would you like to change the name of the Config item `num_node` ?

### ISSUE THREAD

**Issue by aramoto99** [aistairc/aiaccel#289]
I 've received feedback that the name `num_node` in the Config item is confusing. It might be better to change it to a name that feels more natural in both ABCI mode and local mode. Personally, I think `num_workers` would be a good choice.

<hr>

`num_node` という名称が分かりにくいという意見が複数ありました．ABCIモードと．Localモードの両方において，違和感のない名称に変更したほうが良いかもしれません．個人的には `num_workers` が良いかな，と思いました．

**Comment by yoshipon** [comment]
num_workers無難で良いと思います！
