### ISSUE TITLE
Long stderr stops set_result command

### ISSUE THREAD

**Issue by tkokada** [aistairc/aiaccel#333]
**Describe the bug**
aiacce/abci/batch.py でバッチジョブスクリプトが生成されるが，error引数にstderrの出力全てが渡され aiaccel.cli.set_result が呼ばれる．
この時 error引数は bashスクリプトとして呼ばれるのでwhitespaceや", ', \ などがstderrに含まれると正常にスクリプトが認識されず停止する場合がある．

**To Reproduce**
1. feature/one_shot_nas などのレポジトリで examples/nas を ABCIで実行する．
2. バッチジョブスクリプトの python -m aiaccel.cli.set_result ... で停止する．

**Comment by 3bisuoka** [comment]
添付のファイルは今年の４月末にABCIを使用して行ったaiaccel x NASの実験の出力結果(abci_output/run_*.sh.)です．出力内容を見ると'result'のvalueに標準出力が大量に入っていたり"数値"と"convergence"が","が消えて繋がっていたりするのですが，このissueに関係しますか？
[run_000000_sh_o39630745.txt](https://github.com/aistairc/aiaccel/files/13750974/run_000000_sh_o39630745.txt)

**Comment by KanaiYuma-aist** [comment]
@3bisuoka 
'result'に標準出力が入る現象は、下記 pull request で修正した内容と関係していると思われます。
OutputHundler が標準出力を読み取っている途中で、データベースへの書き込み処理が走って途中の標準出力を 'result' として書き込んでしまう現象が過去発生していました。
https://github.com/aistairc/aiaccel/pull/332

**Comment by 3bisuoka** [comment]
@KanaiYuma-aist 
ありがとうございます．
