### ISSUE TITLE
Missing Complete English Documentation

### ISSUE THREAD

**Issue by bagustris** [aistairc/aiaccel#361]
**Is your feature request related to a problem? Please describe.**
This issue related to #55.

The English version documentation pointed to the same Japanese documentation.
https://aiaccel.readthedocs.io/en/latest/index.html

**Describe the solution you'd like**
Provide the correct English translation in English section of documentation.

**Describe alternatives you've considered**
This request may not be implemented since the major user of ABCI are Japanese, but if it is implemented, it will increase users of `aiaccel`, particularly outside the use in ABCI.

**Additional context**
Having `aiaccel` instead of vanilla `optuna` may increase the users of `aiaccel`. I'll try to start to translate the `PO` files from Japanese to English if this proposal is accepted .

**Comment by yoshipon** [comment]
Hi Bagus,

Thank you for opening this issue.
We are now moving to aiaccel v2 (on `develop/v2` branch), a modular implementation of aiaccel to improve its usability.
In v2, the translation is very welcome! Thank you very much!

If you prefer, we can also discuss on Slack or face-by-face in AIST👍

**Comment by bagustris** [comment]
Thanks @yoshipon,

I will take a look at `develop/v2`.

Yes, I will be happy to discuss via Slack/face-to-face.
