### ISSUE TITLE
Documentation pages on GitHub Pages?

### ISSUE THREAD

**Issue by tkokada** [aistairc/aiaccel#366]
**Is your feature request related to a problem? Please describe.**
- We don't update the sphinx documents.
- Only administrator can check the readthedocs management web site.

**Describe the solution you'd like**
- Add a new github action file to build the sphinx documentation and upload to GitHub Pages.

**Describe alternatives you've considered**
- Keep on the readthedocs, but everyone should update the docs when update the codes.
- We need additional payments for GitHub Pages, but not expensive.

**Comment by yoshipon** [comment]
Thank you for opening this issue! I think you have kindly and successfully updated the repository to use GH Pages.
Please also update link URLs in the README*.md
