### ISSUE TITLE
List of features not yet implemented in v2

### ISSUE THREAD

**Issue by KanaiYuma-aist** [aistairc/aiaccel#386]
v1 に実装していて、v2 に未実装の機能一覧

- WIP

**Comment by aramoto99** [comment]
〇: 実装済み
×：未

機能  | v1 | v2 | 備考
--- |---| --- | ---
sobol optimizer | 〇 | × | -
MOTPE optimizer | 〇 | × | -
budget specified grid optimizer | 〇 | × | -
examples  | 〇 | △ | (v1ではベンチマーク関数が多数あるが、v2では現状一つのみ)
可視化ツール(tensorboard) | 〇 | 不要 |-
レポート(CSV)生成機能 | 〇 | 不要 | -
CLIグラフ表示機能 | 〇 | 不要 | -
ドキュメント | 〇 | ×　| 作成中 
カバレッジテスト | 〇 | × | v2 テストコンセプトを見直す必要あり

**Comment by yoshipon** [comment]
@aramoto99 Sobol, MOTPEはOptunaに実装がある理解ですが違いました？ budget specifiedは一旦落としましょう。
可視化ツール、レポート、グラフも同様です。
