### ISSUE TITLE
Prepare document in both Japanese and English on readthedocs.io

### ISSUE THREAD

**Issue by yoshipon** [aistairc/aiaccel#55]
**Is your feature request related to a problem? Please describe.**
The documentation has not been well summarized yet.

**Describe the solution you'd like**
We firstly should summarize what should be summarized in the document...

**Comment by yoshipon** [comment]
ドキュメントは，
1. Overview (トップページ？)
2. Installation
3. User Guide
5. API Reference
6. Contribution Guide
あたりが大項目でしょうか．

3. User Guide には，
3-1. 基本的な使い方
3-2. Configの設定方法
3-3. アーキテクチャの説明？
3-4. 独自オプティマイザの作り方
あたりが書いてあると良いと思います．3-3, 3-4は大項目にしても良いかもしれません．

**Comment by tkokada** [comment]
ありがとうございます。ひとまずこれで作ってみて項目は少しずつブラッシュアップでも良いかなと思います。

場所は現状 docs/manual_jp.md にありますがどうしましょう？Wikiとかに書きます？

**Comment by tkokada** [comment]
ああ、タイトルに readthedocs.io とありますね。

**Comment by yoshipon** [comment]
はい，readthedocs.io にお願いします．
一旦章立て整えて頂いた段階でPR (WIP?) お願いできますでしょうか．

**Comment by tkokada** [comment]
現在の章立てと完了((Done)と記載)の状況

1 オーバービュー (Done)
2 インストレーション
2-1 Linuxインストレーション
2-2 Windowsインストレーション
2-3 MacOSインストレーション
3 利用例
3-1 Sphere関数最適化の例
3-2 ResNet50の最適化の例
3-3 Schwefel関数最適化の例
3-4 Styblinkski-Tang関数最適化の例
3-5 ベンチマーク関数最適化の例
3-6 ラッパー関数作成の例
4 ユーザーガイド
4-1 基本的な使い方 (Done)
4-2 コンフィグレーションの設定ガイド
5 ディベロッパーガイド
5-1 aiaccelアーキテクチャ
5-2 カスタムオプティマイザー作成ガイド(Done)
6 コントリビューションガイド
7 リファレンス
8 コードリファレンス(Done)

**Comment by bagustris** [comment]
Where can I find the complete documentation for English?
This page shows still shows Japanese, although it is in `en/latest`.

https://aiaccel.readthedocs.io/en/latest/
