### ISSUE TITLE
Can't run 'python -m aiaccel.start'

### ISSUE THREAD

**Issue by KanaiYuma-aist** [aistairc/aiaccel#66]
**Is your feature request related to a problem? Please describe.**
By commit 7af665bad62026c0d10fc588ebe94fd724f3b7f7, `python -m aiaccel.start` can not run.

**Comment by KanaiYuma-aist** [comment]
解決策1 
ディレクトリ構造に合わせて
python -m aiaccel.cli.start
に実行コマンドを変更する。

（単純に解決出来ますが、改修でstart.pyのパスが変わる度に
実行コマンドを変更する必要が発生します。）


解決策2 
setup.pyを改修し、グローバルコマンドとして
aiaccel.start
等を実行出来るようにする。
（entry_points を利用 https://setuptools.pypa.io/en/latest/userguide/entry_point.html#dynamic-discovery-of-services-and-plugins）


いずれの解決策を取るとしても、README.mdの改修は必要だと考えています。
ご意見ありましたら、コメントよろしくお願いします。

**Comment by yoshipon** [comment]
ありがとうございます．解決策2で行きましょう．
`aiaccel-*` みたいなコマンドでインストールされるようお願いできますか？

**Comment by KanaiYuma-aist** [comment]
解決策2 実装のpull request を作成しました。 #69
