### ISSUE TITLE
Methods of implementing and presenting default configs

### ISSUE THREAD

**Issue by tkmnet** [aistairc/aiaccel#67]
**Is your feature request related to a problem? Please describe.**
The items supported by the config file are not clearly listed, making it difficult to find them.

**Describe the solution you'd like**
It is preferable to be provided with a fully described config file.

**Describe alternatives you've considered**
Instead of defining default values for configurations in code(config.py), define them in a fully described default config file(default_config.yaml?), and preload it in config.py. The user can easily understand the supported values by referring to the file.

**Comment by yoshipon** [comment]
TODO: Hydraのお作法を確認する．
