### ISSUE TITLE
Suggestion on log message sorting function

### ISSUE THREAD

**Issue by tkmnet** [aistairc/aiaccel#75]
In the case of a conditional branch written in [aiaccel/util/logger.py](https://github.com/aistairc/aiaccel/blob/main/aiaccel/util/logger.py), important information may be dropped to a lower level.
If using the 'in s:' statement in the branching, I think you should write it in the ordering of level.

**Comment by tkmnet** [comment]
Sorry... I mistook it as the message sorting function, which is to get a level from a complete message.

**Comment by tkokada** [comment]
そのほうが良いですね。環境変数から参照で良いと思います。
