### ISSUE TITLE
Redesign: (inner_)loop_{pre/post}_process 

### ISSUE THREAD

**Issue by aramoto99** [aistairc/aiaccel#80]
現在の処理フローは概ね次のようになっていますが，
~~~ python
pre_process()
loop_pre_process()
while True:
    inner_loop_pre_process()
    inner_loop_main_process()
    inner_loop_post_process()
    check_error()
loop_post_process()
post_process()
~~~

次の関数は，可能ならば前後の処理に統合したほうが良いかも？
- loop_pre_process
- loop_post_process
- inner_loop_pre_process
- inner_loop_post_process

**Comment by yoshipon** [comment]
@tkokada 本件ご意見頂けると幸いです。

**Comment by tkokada** [comment]
遅くなりました．一応手広く用意しておいただけなので別に良いと思いますよ．

**Comment by yoshipon** [comment]
ありがとうございます。現状使われていないようであれば、統一をお願いします。@aramoto99
