### ISSUE TITLE
Check database synchronization

### ISSUE THREAD

**Issue by tkmnet** [aistairc/aiaccel#89]
https://github.com/aistairc/aiaccel/blob/f8ad49a8dacf3b14c9d5b4e2050260bcc47d49f7/aiaccel/storage/abstruct.py#L21

I think 'check_same_thread' should be True, which is the default value.
If it is False, users should be responsible for the synchronization when writing values.

Moreover, I recommend verifying the framework-side synchronization on multiple computers. (@yoshipon mentioned it on Slack)

**Comment by yoshipon** [comment]
@aramoto99 こちら，確認お願いします．
